sudo: required
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
before_script:
  - sudo chmod 444 ./test/unwritableTarget
  - sudo chmod 777 ./test/writableTarget
script: "sudo npm test"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
